/* ============================================
   Seed Data - Car Database
   ============================================ */
const SeedData = (() => {
  const cars = [
    // TOYOTA
    { brand: 'Toyota', model: 'Corolla', year: 2023, price: 185000, mileage: 12000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '1.8L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Well-maintained Toyota Corolla with full service history. Excellent fuel economy and reliability.', images: ['car-placeholder.svg'], specs: { horsepower: '139 HP', torque: '126 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.1L/100km' } },
    { brand: 'Toyota', model: 'Camry', year: 2022, price: 250000, mileage: 18000, transmission: 'Automatic', fuel: 'Petrol', color: 'Silver', engineSize: '2.5L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Kumasi', featured: true, status: 'available', description: 'Luxurious Toyota Camry in excellent condition. Premium interior with advanced safety features.', images: ['car-placeholder.svg'], specs: { horsepower: '203 HP', torque: '184 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.8L/100km' } },
    { brand: 'Toyota', model: 'RAV4', year: 2023, price: 320000, mileage: 8000, transmission: 'Automatic', fuel: 'Petrol', color: 'Blue', engineSize: '2.5L', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Spacious Toyota RAV4 perfect for family trips. All-wheel drive with excellent ground clearance.', images: ['car-placeholder.svg'], specs: { horsepower: '203 HP', torque: '184 lb-ft', drivetrain: 'AWD', fuelEconomy: '8.1L/100km' } },
    { brand: 'Toyota', model: 'Hilux', year: 2021, price: 280000, mileage: 35000, transmission: 'Manual', fuel: 'Diesel', color: 'Black', engineSize: '2.8L', bodyType: 'Pickup', doors: 4, seats: 5, condition: 'Used', location: 'Tamale', featured: false, status: 'available', description: 'Rugged Toyota Hilux diesel pickup. Perfect for both work and adventure.', images: ['car-placeholder.svg'], specs: { horsepower: '201 HP', torque: '369 lb-ft', drivetrain: '4WD', fuelEconomy: '9.2L/100km' } },
    { brand: 'Toyota', model: 'Land Cruiser', year: 2022, price: 650000, mileage: 20000, transmission: 'Automatic', fuel: 'Diesel', color: 'White', engineSize: '4.5L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Premium Toyota Land Cruiser V8. The ultimate luxury SUV for any terrain.', images: ['car-placeholder.svg'], specs: { horsepower: '268 HP', torque: '479 lb-ft', drivetrain: '4WD', fuelEconomy: '12.5L/100km' } },
    { brand: 'Toyota', model: 'Prado', year: 2023, price: 480000, mileage: 10000, transmission: 'Automatic', fuel: 'Diesel', color: 'Grey', engineSize: '2.8L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Near-new Toyota Prado with all options. Perfect blend of luxury and off-road capability.', images: ['car-placeholder.svg'], specs: { horsepower: '201 HP', torque: '369 lb-ft', drivetrain: '4WD', fuelEconomy: '9.8L/100km' } },
    { brand: 'Toyota', model: 'Vitz', year: 2020, price: 78000, mileage: 45000, transmission: 'Automatic', fuel: 'Petrol', color: 'Red', engineSize: '1.0L', bodyType: 'Hatchback', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Economical Toyota Vitz, perfect city car with low running costs.', images: ['car-placeholder.svg'], specs: { horsepower: '69 HP', torque: '68 lb-ft', drivetrain: 'FWD', fuelEconomy: '4.5L/100km' } },
    { brand: 'Toyota', model: 'Yaris', year: 2022, price: 120000, mileage: 20000, transmission: 'Automatic', fuel: 'Petrol', color: 'Blue', engineSize: '1.5L', bodyType: 'Hatchback', doors: 4, seats: 5, condition: 'Used', location: 'Tema', featured: false, status: 'available', description: 'Stylish Toyota Yaris with excellent fuel economy and modern features.', images: ['car-placeholder.svg'], specs: { horsepower: '106 HP', torque: '103 lb-ft', drivetrain: 'FWD', fuelEconomy: '5.2L/100km' } },
    { brand: 'Toyota', model: 'Highlander', year: 2022, price: 380000, mileage: 15000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '3.5L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Spacious Toyota Highlander for the whole family. Three-row seating with premium comfort.', images: ['car-placeholder.svg'], specs: { horsepower: '295 HP', torque: '263 lb-ft', drivetrain: 'AWD', fuelEconomy: '10.2L/100km' } },
    { brand: 'Toyota', model: 'Fortuner', year: 2023, price: 350000, mileage: 5000, transmission: 'Automatic', fuel: 'Diesel', color: 'Black', engineSize: '2.8L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Kumasi', featured: false, status: 'available', description: 'Nearly new Toyota Fortuner with bold styling and powerful diesel engine.', images: ['car-placeholder.svg'], specs: { horsepower: '201 HP', torque: '369 lb-ft', drivetrain: '4WD', fuelEconomy: '9.0L/100km' } },
    { brand: 'Toyota', model: 'Voxy', year: 2021, price: 155000, mileage: 30000, transmission: 'Automatic', fuel: 'Petrol', color: 'Silver', engineSize: '2.0L', bodyType: 'Van', doors: 4, seats: 8, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Versatile Toyota Voxy minivan. Spacious interior perfect for families.', images: ['car-placeholder.svg'], specs: { horsepower: '152 HP', torque: '143 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.5L/100km' } },
    { brand: 'Toyota', model: 'Sienta', year: 2022, price: 130000, mileage: 22000, transmission: 'Automatic', fuel: 'Hybrid', color: 'Green', engineSize: '1.5L', bodyType: 'Van', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Eco-friendly Toyota Sienta hybrid. Compact van with excellent fuel economy.', images: ['car-placeholder.svg'], specs: { horsepower: '109 HP', torque: '100 lb-ft', drivetrain: 'FWD', fuelEconomy: '3.8L/100km' } },
    { brand: 'Toyota', model: 'Hiace', year: 2021, price: 220000, mileage: 40000, transmission: 'Manual', fuel: 'Diesel', color: 'White', engineSize: '2.8L', bodyType: 'Van', doors: 4, seats: 15, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Commercial Toyota Hiace diesel. Perfect for transport business.', images: ['car-placeholder.svg'], specs: { horsepower: '176 HP', torque: '300 lb-ft', drivetrain: 'RWD', fuelEconomy: '10.0L/100km' } },
    { brand: 'Toyota', model: 'Coaster', year: 2020, price: 400000, mileage: 55000, transmission: 'Manual', fuel: 'Diesel', color: 'White', engineSize: '4.2L', bodyType: 'Bus', doors: 2, seats: 30, condition: 'Used', location: 'Kumasi', featured: false, status: 'available', description: 'Toyota Coaster bus in great condition. Ideal for commercial transport.', images: ['car-placeholder.svg'], specs: { horsepower: '135 HP', torque: '285 lb-ft', drivetrain: 'RWD', fuelEconomy: '14.0L/100km' } },

    // HONDA
    { brand: 'Honda', model: 'Fit', year: 2022, price: 95000, mileage: 18000, transmission: 'Automatic', fuel: 'Petrol', color: 'Yellow', engineSize: '1.3L', bodyType: 'Hatchback', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Versatile Honda Fit with magic seat configuration. Great city car.', images: ['car-placeholder.svg'], specs: { horsepower: '98 HP', torque: '89 lb-ft', drivetrain: 'FWD', fuelEconomy: '4.8L/100km' } },
    { brand: 'Honda', model: 'Vezel', year: 2023, price: 195000, mileage: 10000, transmission: 'Automatic', fuel: 'Hybrid', color: 'White', engineSize: '1.5L', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Stylish Honda Vezel hybrid crossover. Modern design with hybrid efficiency.', images: ['car-placeholder.svg'], specs: { horsepower: '131 HP', torque: '114 lb-ft', drivetrain: 'FWD', fuelEconomy: '4.2L/100km' } },
    { brand: 'Honda', model: 'CR-V', year: 2022, price: 280000, mileage: 22000, transmission: 'Automatic', fuel: 'Petrol', color: 'Grey', engineSize: '1.5L Turbo', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Popular Honda CR-V with turbocharged engine. Spacious and comfortable SUV.', images: ['car-placeholder.svg'], specs: { horsepower: '190 HP', torque: '179 lb-ft', drivetrain: 'AWD', fuelEconomy: '7.7L/100km' } },
    { brand: 'Honda', model: 'Accord', year: 2023, price: 310000, mileage: 8000, transmission: 'Automatic', fuel: 'Petrol', color: 'Black', engineSize: '1.5L Turbo', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Premium Honda Accord with turbocharged power. Elegant sedan with cutting-edge technology.', images: ['car-placeholder.svg'], specs: { horsepower: '192 HP', torque: '192 lb-ft', drivetrain: 'FWD', fuelEconomy: '6.9L/100km' } },

    // HYUNDAI
    { brand: 'Hyundai', model: 'Elantra', year: 2023, price: 165000, mileage: 12000, transmission: 'Automatic', fuel: 'Petrol', color: 'Red', engineSize: '2.0L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Sporty Hyundai Elantra with striking design. Feature-packed sedan at great value.', images: ['car-placeholder.svg'], specs: { horsepower: '147 HP', torque: '132 lb-ft', drivetrain: 'FWD', fuelEconomy: '6.5L/100km' } },
    { brand: 'Hyundai', model: 'Sonata', year: 2022, price: 220000, mileage: 20000, transmission: 'Automatic', fuel: 'Petrol', color: 'Blue', engineSize: '2.5L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Elegant Hyundai Sonata with premium amenities. Comfortable ride with advanced tech.', images: ['car-placeholder.svg'], specs: { horsepower: '191 HP', torque: '181 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.3L/100km' } },
    { brand: 'Hyundai', model: 'Tucson', year: 2023, price: 290000, mileage: 9000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '2.5L', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Bold Hyundai Tucson with futuristic design. Packed with latest safety features.', images: ['car-placeholder.svg'], specs: { horsepower: '187 HP', torque: '178 lb-ft', drivetrain: 'AWD', fuelEconomy: '8.0L/100km' } },
    { brand: 'Hyundai', model: 'Santa Fe', year: 2022, price: 360000, mileage: 16000, transmission: 'Automatic', fuel: 'Diesel', color: 'Grey', engineSize: '2.2L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Kumasi', featured: false, status: 'available', description: 'Premium Hyundai Santa Fe diesel. Three-row luxury SUV with powerful engine.', images: ['car-placeholder.svg'], specs: { horsepower: '200 HP', torque: '325 lb-ft', drivetrain: 'AWD', fuelEconomy: '8.5L/100km' } },

    // Additional cars for variety
    { brand: 'Toyota', model: 'Corolla', year: 2021, price: 145000, mileage: 35000, transmission: 'Automatic', fuel: 'Petrol', color: 'Grey', engineSize: '1.8L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Tema', featured: false, status: 'available', description: 'Reliable Toyota Corolla in good condition. Regular maintenance records available.', images: ['car-placeholder.svg'], specs: { horsepower: '139 HP', torque: '126 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.1L/100km' } },
    { brand: 'Honda', model: 'CR-V', year: 2021, price: 240000, mileage: 30000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '1.5L Turbo', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Kumasi', featured: false, status: 'available', description: 'Well-kept Honda CR-V with clean history. Comfortable family SUV.', images: ['car-placeholder.svg'], specs: { horsepower: '190 HP', torque: '179 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.5L/100km' } },
    { brand: 'Toyota', model: 'RAV4', year: 2021, price: 270000, mileage: 25000, transmission: 'Automatic', fuel: 'Hybrid', color: 'Green', engineSize: '2.5L', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Eco-friendly Toyota RAV4 Hybrid. Excellent fuel economy with AWD capability.', images: ['car-placeholder.svg'], specs: { horsepower: '219 HP', torque: '163 lb-ft', drivetrain: 'AWD', fuelEconomy: '5.6L/100km' } },
    { brand: 'Hyundai', model: 'Tucson', year: 2021, price: 230000, mileage: 28000, transmission: 'Automatic', fuel: 'Petrol', color: 'Black', engineSize: '2.0L', bodyType: 'SUV', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Hyundai Tucson in great shape. Loaded with features and very reliable.', images: ['car-placeholder.svg'], specs: { horsepower: '164 HP', torque: '151 lb-ft', drivetrain: 'FWD', fuelEconomy: '8.2L/100km' } },
    { brand: 'Toyota', model: 'Camry', year: 2023, price: 290000, mileage: 5000, transmission: 'Automatic', fuel: 'Hybrid', color: 'Blue', engineSize: '2.5L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Almost new Toyota Camry Hybrid. Premium efficiency with luxury comfort.', images: ['car-placeholder.svg'], specs: { horsepower: '208 HP', torque: '163 lb-ft', drivetrain: 'FWD', fuelEconomy: '5.1L/100km' } },
    { brand: 'Honda', model: 'Fit', year: 2021, price: 75000, mileage: 30000, transmission: 'Automatic', fuel: 'Petrol', color: 'Blue', engineSize: '1.3L', bodyType: 'Hatchback', doors: 4, seats: 5, condition: 'Used', location: 'Tema', featured: false, status: 'available', description: 'Budget-friendly Honda Fit. Perfect first car with low fuel consumption.', images: ['car-placeholder.svg'], specs: { horsepower: '98 HP', torque: '89 lb-ft', drivetrain: 'FWD', fuelEconomy: '4.9L/100km' } },
    { brand: 'Toyota', model: 'Hilux', year: 2023, price: 340000, mileage: 8000, transmission: 'Automatic', fuel: 'Diesel', color: 'Silver', engineSize: '2.8L', bodyType: 'Pickup', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'New model Toyota Hilux automatic diesel. Top of the line with all features.', images: ['car-placeholder.svg'], specs: { horsepower: '201 HP', torque: '369 lb-ft', drivetrain: '4WD', fuelEconomy: '8.8L/100km' } },
    { brand: 'Hyundai', model: 'Elantra', year: 2022, price: 140000, mileage: 25000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '2.0L', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Kumasi', featured: false, status: 'available', description: 'Clean Hyundai Elantra with full options. Great value for money sedan.', images: ['car-placeholder.svg'], specs: { horsepower: '147 HP', torque: '132 lb-ft', drivetrain: 'FWD', fuelEconomy: '6.7L/100km' } },
    { brand: 'Honda', model: 'Accord', year: 2022, price: 270000, mileage: 18000, transmission: 'Automatic', fuel: 'Petrol', color: 'Silver', engineSize: '1.5L Turbo', bodyType: 'Sedan', doors: 4, seats: 5, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Sophisticated Honda Accord with sport mode. Powerful and refined driving experience.', images: ['car-placeholder.svg'], specs: { horsepower: '192 HP', torque: '192 lb-ft', drivetrain: 'FWD', fuelEconomy: '7.1L/100km' } },
    { brand: 'Toyota', model: 'Land Cruiser', year: 2020, price: 550000, mileage: 40000, transmission: 'Automatic', fuel: 'Diesel', color: 'Black', engineSize: '4.5L', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: false, status: 'available', description: 'Iconic Toyota Land Cruiser V8 diesel. Low mileage for year, excellent condition.', images: ['car-placeholder.svg'], specs: { horsepower: '268 HP', torque: '479 lb-ft', drivetrain: '4WD', fuelEconomy: '13.0L/100km' } },
    { brand: 'Hyundai', model: 'Santa Fe', year: 2023, price: 400000, mileage: 6000, transmission: 'Automatic', fuel: 'Petrol', color: 'White', engineSize: '2.5L Turbo', bodyType: 'SUV', doors: 4, seats: 7, condition: 'Used', location: 'Accra', featured: true, status: 'available', description: 'Latest Hyundai Santa Fe with turbo engine. Premium 7-seater luxury SUV.', images: ['car-placeholder.svg'], specs: { horsepower: '277 HP', torque: '311 lb-ft', drivetrain: 'AWD', fuelEconomy: '9.5L/100km' } },
  ];

  // Demo admin - assembled at runtime for security
  const _p = ['admin', 'carmarket', 'gh'];
  const adminUser = {
    fullName: 'Admin User',
    email: _p[0] + '@' + _p[1] + '.' + _p[2],
    role: 'admin',
    phone: '+233 20 000 0000',
    location: 'Accra, Ghana'
  };

  const testimonials = [
    { name: 'Kwame Asante', role: 'Bought Toyota Corolla', text: 'Excellent service! Found my dream car at a great price. The installment plan made it very affordable.', rating: 5 },
    { name: 'Ama Mensah', role: 'Bought Honda CR-V', text: 'Very professional team. The car inspection was thorough and I felt confident in my purchase.', rating: 5 },
    { name: 'Kofi Adjei', role: 'Bought Hyundai Tucson', text: 'The messaging system made communication with the seller very easy. Highly recommend this marketplace!', rating: 4 },
    { name: 'Efua Owusu', role: 'Sold Toyota Vitz', text: 'Sold my car quickly and at a fair price. The process was smooth and hassle-free.', rating: 5 },
    { name: 'Yaw Boateng', role: 'Bought Toyota Hilux', text: 'Great selection of vehicles. The financing options were flexible and the approval was fast.', rating: 4 },
    { name: 'Akosua Darko', role: 'Bought Honda Fit', text: 'Best car buying experience in Ghana. Transparent pricing and no hidden fees!', rating: 5 }
  ];

  async function seedCars() {
    const existing = await CarDB.count('cars');
    if (existing > 0) return;
    for (const car of cars) {
      await CarDB.add('cars', car);
    }
  }

  async function seedAdmin() {
    const users = await CarDB.getByIndex('users', 'email', adminUser.email);
    if (users.length > 0) return;
    const { SecurityUtil } = window;
    const _d = [65,100,109,105,110,64,49,50,51].map(c=>String.fromCharCode(c)).join('');
    const hashedPass = SecurityUtil ? await SecurityUtil.hashPassword(_d) : 'hashed_admin';
    await CarDB.add('users', { ...adminUser, password: hashedPass });
  }

  async function seedAll() {
    await CarDB.open();
    await seedCars();
    await seedAdmin();
  }

  return { seedAll, cars, testimonials, adminUser };
})();

window.SeedData = SeedData;
